# Generated by Django 5.2.6 on 2025-09-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicmodel',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='music/'),
        ),
    ]
