# Generated by Django 5.2.6 on 2025-10-15 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_commentdislikemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='replymodel',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='posts.postmodel'),
            preserve_default=False,
        ),
    ]
