# Generated by Django 5.2.6 on 2025-10-18 09:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_replycommentdislikemodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='reposts',
            field=models.ManyToManyField(blank=True, null=True, related_name='reposts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='saved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='saves',
            field=models.ManyToManyField(blank=True, null=True, related_name='saved_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
