# Generated by Django 5.2.6 on 2025-10-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_postmodel_reposts_postmodel_saved_postmodel_saves'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='genre',
            field=models.CharField(blank=True, choices=[('SINGING_DANCING', 'Singing_dancing'), ('COMEDY', 'Comedy'), ('SPORTS', 'Sports'), ('ANIME_COMICS', 'Anime_comics'), ('RELATIONSHIP', 'Relationship'), ('SHOWS', 'Shows'), ('DAILY_LIFE', 'Daily_life'), ('BEAUTY_CARE', 'Beauty_care'), ('GAMES', 'Games'), ('SOCIETY', 'Society'), ('OUTFIT', 'Outfit'), ('CARS', 'Cars'), ('FOOD', 'Food'), ('ANIMALS', 'Animals'), ('FAMILY', 'Family'), ('DRAMA', 'Drama'), ('FITNESS_HEALTH', 'Fitness_health'), ('EDUCATION', 'Education'), ('TECHNOLOGY', 'Technology')], max_length=30, null=True),
        ),
    ]
