# Generated by Django 5.2.6 on 2025-10-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_postmodel_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmodel',
            name='notif_type',
            field=models.CharField(choices=[('LIKE', 'Like'), ('FOLLOW', 'Follow'), ('COMMENT', 'Comment'), ('REPLY', 'reply')], max_length=20),
        ),
    ]
