# Generated by Django 5.2.6 on 2025-11-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_repostmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='repostmodel',
            name='text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
